# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.Quit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Quit_btn.setGeometry(QtCore.QRect(980, 670, 90, 28))
        self.Quit_btn.setObjectName("Quit_btn")

        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(10, 0, 1081, 661))
        self.tabs.setObjectName("tabs")

        self.groups_tab = QtWidgets.QWidget()
        self.groups_tab.setObjectName("groups_tab")

        self.delGroup_btn = QtWidgets.QPushButton(self.groups_tab)
        self.delGroup_btn.setGeometry(QtCore.QRect(100, 600, 90, 28))
        self.delGroup_btn.setObjectName("delGroup_btn")

        self.group_tbl = QtWidgets.QTableWidget(self.groups_tab)
        self.group_tbl.setGeometry(QtCore.QRect(0, 11, 1061, 581))
        self.group_tbl.setObjectName("group_tbl")
        self.group_tbl.setColumnCount(0)
        self.group_tbl.setRowCount(0)

        self.addGroup_btn = QtWidgets.QPushButton(self.groups_tab)
        self.addGroup_btn.setGeometry(QtCore.QRect(0, 600, 90, 28))
        self.addGroup_btn.setObjectName("addGroup_btn")

        self.tabs.addTab(self.groups_tab, "")
        self.courses_tab = QtWidgets.QWidget()
        self.courses_tab.setObjectName("courses_tab")

        self.tableView = QtWidgets.QTableView(self.courses_tab)
        self.tableView.setGeometry(QtCore.QRect(0, 10, 1061, 581))
        self.tableView.setObjectName("tableView")

        self.addLec_btn = QtWidgets.QPushButton(self.courses_tab)
        self.addLec_btn.setGeometry(QtCore.QRect(0, 600, 90, 28))
        self.addLec_btn.setObjectName("addLec_btn")
        self.delLec_btn = QtWidgets.QPushButton(self.courses_tab)
        self.delLec_btn.setGeometry(QtCore.QRect(970, 600, 90, 28))
        self.delLec_btn.setObjectName("delLec_btn")

        self.tabs.addTab(self.courses_tab, "")
        self.employes_tab = QtWidgets.QWidget()
        self.employes_tab.setObjectName("employes_tab")

        self.tableWidget = QtWidgets.QTableWidget(self.employes_tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 10, 1061, 581))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.addEmpl_btn = QtWidgets.QPushButton(self.employes_tab)
        self.addEmpl_btn.setGeometry(QtCore.QRect(0, 600, 90, 28))
        self.addEmpl_btn.setObjectName("addEmpl_btn")
        self.delEmpl_btn = QtWidgets.QPushButton(self.employes_tab)
        self.delEmpl_btn.setGeometry(QtCore.QRect(100, 600, 90, 28))
        self.delEmpl_btn.setObjectName("delEmpl_btn")

        self.tabs.addTab(self.employes_tab, "")
        self.working_tab = QtWidgets.QWidget()
        self.working_tab.setObjectName("working_tab")

        self.tableView_2 = QtWidgets.QTableView(self.working_tab)
        self.tableView_2.setGeometry(QtCore.QRect(0, 10, 1061, 581))
        self.tableView_2.setObjectName("tableView_2")

        self.addFlag_btn = QtWidgets.QPushButton(self.working_tab)
        self.addFlag_btn.setGeometry(QtCore.QRect(0, 600, 90, 28))
        self.addFlag_btn.setObjectName("addFlag_btn")
        self.delFlag_btn = QtWidgets.QPushButton(self.working_tab)
        self.delFlag_btn.setGeometry(QtCore.QRect(100, 600, 90, 28))
        self.delFlag_btn.setObjectName("delFlag_btn")

        self.tabs.addTab(self.working_tab, "")
        self.points_tab = QtWidgets.QWidget()
        self.points_tab.setObjectName("points_tab")
        self.tabs.addTab(self.points_tab, "")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Softik pro tajemnika"))

        self.Quit_btn.setText(_translate("MainWindow", "Quit"))

        self.delGroup_btn.setText(_translate("MainWindow", "Odebrat"))
        self.addGroup_btn.setText(_translate("MainWindow", "Přidat"))

        self.tabs.setTabText(self.tabs.indexOf(self.groups_tab), _translate("MainWindow", "Skupiny"))
        self.addLec_btn.setText(_translate("MainWindow", "Přidat"))
        self.delLec_btn.setText(_translate("MainWindow", "Smazat"))
        
        self.tabs.setTabText(self.tabs.indexOf(self.courses_tab), _translate("MainWindow", "Předměty"))
        self.addEmpl_btn.setText(_translate("MainWindow", "Přidat"))
        self.delEmpl_btn.setText(_translate("MainWindow", "Odebrat"))
        
        self.tabs.setTabText(self.tabs.indexOf(self.employes_tab), _translate("MainWindow", "Zaměstnanci"))
        self.addFlag_btn.setText(_translate("MainWindow", "Vytvořit"))
        
        self.delFlag_btn.setText(_translate("MainWindow", "Smazat"))
        self.tabs.setTabText(self.tabs.indexOf(self.working_tab), _translate("MainWindow", "Pracovní štítky"))
        self.tabs.setTabText(self.tabs.indexOf(self.points_tab), _translate("MainWindow", "Body"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
